services:
  - type: web
    name: wafi-portfolio
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Wafi Portfolio
      - key: APP_KEY
        value: base64:NDBiMzUwMjktY2UyNC00MWZhLTk4MzEtZWNkMjZiZGUyZTk3NzdlMGVjMWUtMzZjMS00MTkyLWJhNWMtM2Q1NjNiZWIyZjIx
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
